apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: xub0wplb7-nodejs
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jsmid/rhtap-qe-nodejs:be83a91835bf34f8d9c5ffc85412ae21533de866@sha256:f2205823c433d356a2282fc1a89137e1b0142f3943338370b420a00936668948
          name: container-image
